apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: hello
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: jonhawkes/hello:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/opt/ol/wlp/usr/shared"
          name: hello-volume
        ports:
        - containerPort: 8080
      volumes:
      - name: hello-volume
        persistentVolumeClaim:
          claimName: recovery-claim
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: peer-recovery-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /peer-recovery-test/hello
        backend:
          serviceName: hello-service
          servicePort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recovery-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
  selector: 
    matchLabels:
      purpose: recovery-logs
