apiVersion: v1
kind: Pod
metadata:
  name: pv-cleaner
spec:
  restartPolicy: Never
  containers:
  - name: pv-cleaner
    image: k8s.gcr.io/busybox
    command: ["/bin/sh", "-c", "rm -rf /recovery/*"]
    volumeMounts:
    - mountPath: "/recovery"
      name: recovery-volume
  volumes:
  - name: recovery-volume
    persistentVolumeClaim:
      claimName: recovery-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recovery-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
  selector: 
    matchLabels:
      purpose: recovery-logs
